--------------------------------------------------------
--  File created - Tuesday-December-27-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ERS_REIMBURSEMENT
--------------------------------------------------------

  CREATE TABLE "ERS"."ERS_REIMBURSEMENT" 
   (	"REIMB_ID" NUMBER, 
	"REIMB_AMOUNT" NUMBER, 
	"REIMB_SUBMITTED" TIMESTAMP (6), 
	"REIMB_RESOLVED" TIMESTAMP (6), 
	"REIMB_DESCRIPTION" VARCHAR2(250 BYTE), 
	"REIMB_AUTHOR" NUMBER, 
	"REIMB_RESOLVER" NUMBER, 
	"REIMB_STATUS_ID" NUMBER, 
	"REIMB_TYPE_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ERS_REIMBURSEMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ERS"."ERS_REIMBURSEMENT_PK" ON "ERS"."ERS_REIMBURSEMENT" ("REIMB_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ERS_REIMBURSEMENT
--------------------------------------------------------

  ALTER TABLE "ERS"."ERS_REIMBURSEMENT" MODIFY ("REIMB_TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "ERS"."ERS_REIMBURSEMENT" MODIFY ("REIMB_STATUS_ID" NOT NULL ENABLE);
  ALTER TABLE "ERS"."ERS_REIMBURSEMENT" MODIFY ("REIMB_AUTHOR" NOT NULL ENABLE);
  ALTER TABLE "ERS"."ERS_REIMBURSEMENT" MODIFY ("REIMB_SUBMITTED" NOT NULL ENABLE);
  ALTER TABLE "ERS"."ERS_REIMBURSEMENT" MODIFY ("REIMB_AMOUNT" NOT NULL ENABLE);
  ALTER TABLE "ERS"."ERS_REIMBURSEMENT" ADD CONSTRAINT "ERS_REIMBURSEMENT_PK" PRIMARY KEY ("REIMB_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ERS"."ERS_REIMBURSEMENT" MODIFY ("REIMB_ID" NOT NULL ENABLE);
