--------------------------------------------------------
--  File created - Tuesday-December-27-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ERS_USERS
--------------------------------------------------------

  CREATE TABLE "ERS"."ERS_USERS" 
   (	"ERS_USERS_ID" NUMBER, 
	"ERS_USERNAME" VARCHAR2(50 BYTE), 
	"ERS_PASSWORD" VARCHAR2(100 BYTE), 
	"USER_FIRST_NAME" VARCHAR2(100 BYTE), 
	"USER_LAST_NAME" VARCHAR2(100 BYTE), 
	"USER_EMAIL" VARCHAR2(150 BYTE), 
	"USER_ROLE_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ERS_USERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ERS"."ERS_USERS_PK" ON "ERS"."ERS_USERS" ("ERS_USERS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ERS_USERS_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "ERS"."ERS_USERS_UK1" ON "ERS"."ERS_USERS" ("ERS_USERNAME", "USER_EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ERS_USERS
--------------------------------------------------------

  ALTER TABLE "ERS"."ERS_USERS" MODIFY ("USER_ROLE_ID" NOT NULL ENABLE);
  ALTER TABLE "ERS"."ERS_USERS" MODIFY ("USER_EMAIL" NOT NULL ENABLE);
  ALTER TABLE "ERS"."ERS_USERS" MODIFY ("USER_LAST_NAME" NOT NULL ENABLE);
  ALTER TABLE "ERS"."ERS_USERS" MODIFY ("USER_FIRST_NAME" NOT NULL ENABLE);
  ALTER TABLE "ERS"."ERS_USERS" MODIFY ("ERS_PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "ERS"."ERS_USERS" MODIFY ("ERS_USERNAME" NOT NULL ENABLE);
  ALTER TABLE "ERS"."ERS_USERS" ADD CONSTRAINT "ERS_USERS__UNV1" UNIQUE ("ERS_USERNAME", "USER_EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ERS"."ERS_USERS" ADD CONSTRAINT "ERS_USERS_PK" PRIMARY KEY ("ERS_USERS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ERS"."ERS_USERS" MODIFY ("ERS_USERS_ID" NOT NULL ENABLE);
