--------------------------------------------------------
--  File created - Tuesday-December-27-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ERS_USER_ROLES
--------------------------------------------------------

  CREATE TABLE "ERS"."ERS_USER_ROLES" 
   (	"ERS_USER_ROLE_ID" NUMBER, 
	"USER_ROLE" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ERS_USER_ROLES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ERS"."ERS_USER_ROLES_PK" ON "ERS"."ERS_USER_ROLES" ("ERS_USER_ROLE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ERS_USER_ROLES
--------------------------------------------------------

  ALTER TABLE "ERS"."ERS_USER_ROLES" MODIFY ("USER_ROLE" NOT NULL ENABLE);
  ALTER TABLE "ERS"."ERS_USER_ROLES" ADD CONSTRAINT "ERS_USER_ROLES_PK" PRIMARY KEY ("ERS_USER_ROLE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ERS"."ERS_USER_ROLES" MODIFY ("ERS_USER_ROLE_ID" NOT NULL ENABLE);
